### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by xbjfk** [CubeStuffs/CubeTime#1]
- [x] number of solves
- [x] best avg of 5, 12, 100
- [x] current average of 5, 12, 100
- [x] time history graph
- [x] time trend graph - adjustable number of columns
- [x] median
- [x] median on time distribution graph  
- [x] account for +2s, DNFs
- [x] worst solve
- [x] best/worst possible average
- [x] time needed to get average with 4 solves
- [ ] make stats multithreaded/async
- [x] avg, mean of avg, mean
- [ ] PB history, list + search
- [ ] standard deviation
- [ ] total time spent solving
- [ ] global stats - favourite event/session, github commit like history
- [ ] graph of inspection time
- [ ] WCA integration - past PBs, show NR/CR/WR placing, import dataset for calculation - api spec [here](https://github.com/thewca/worldcubeassociation.org/tree/master/WcaOnRails/spec/requests)
  - [ ] ask for wca ID in onboarding

**Comment by pdtxie** [comment]
see #74, closing this
