### ISSUE TITLE
CRITICAL - multitouch stopwatchmanager bugs

### ISSUE THREAD

**Issue by pdtxie** [CubeStuffs/CubeTime#12]
- timer start:
  - using one finger to start, then adding touch with another causes timer to be green and not to start

- timer stop:
  - using one finger to stop and then adding touch with another causes timer to stay red and requires an additional touch to reset back to default state

- timer stop:
  - using two (or more fingers) to stop will NOT stop the timer, when it should

**Comment by xbjfk** [comment]
fixed
