### ISSUE TITLE
Voice Inspection Announcement Toggle With iPhone mute switch

### ISSUE THREAD

**Issue by Wardeneo** [CubeStuffs/CubeTime#140]
Hi guys, amazing update today!

Would it be possible in the future to add a toggle switch in settings to enable inspection voice to be also be muted by iPhone mute switch like the boop option please

just means if I’m cubing and dont want to disturb people, my phone is often muted and this could mute the voice announcement aswell.

could possibly make a toggle switch in settings? to enable/disable this feature with both voice and boop so people that like announcements to stay even when phone is muted could keep it and people like myself who want it muted when phone is muted could have that.

again, amazing update today 👌🏾

cheers liam

**Comment by pdtxie** [comment]
Hey Wardeneo, unfortunately I am unable to play the voice alert through system sounds due to software limitations. At this point in time, the best approach will be to just mute your master (media) sound.

If Apple ever changes this feature, I'll look into this again. Sorry!

**Comment by Wardeneo** [comment]
No worries mate I’ll just use boop option for now 

cheers liam

**Comment by pdtxie** [comment]
Actually... I've found something when trying to fix another issue. Will keep you updated.

**Comment by pdtxie** [comment]
added :)
