### ISSUE TITLE
[Feature] Quick Switch between sessions

### ISSUE THREAD

**Issue by Lollipop1445** [CubeStuffs/CubeTime#142]
Sometimes I like to switch quickly between different puzzles but the method of actual using a different session in the app is kind of long. Also sometime I forget what session I’m in. For the switching, something like a puzzle drop-down for playground mode could be implemented to where it shows the session. To be clear, I’m not saying get rid of the sessions tab, just make a quick switch function along with the dedicated tab. For the forgetting, maybe you could make the session banner/name more prominent and in the middle of screen to improve visibility.

**Comment by pdtxie** [comment]
The new v2 update now shows the session name as the default instead. We may look into adding a dropdown for a sessions quick switch in the near future.
