### ISSUE TITLE
Voice alert turns of music

### ISSUE THREAD

**Issue by Hannawiden** [CubeStuffs/CubeTime#143]
During inspection, the voice alert turns of any background sounds such as Spotify, and you have to manually turn it on. Is it possible for music etc to restart after the alert, or to not be stopped at all? 

 - Device: iPhone 13 pro 
 - OS: iOS 16.3.1
 - App version 2.0

I’m not sure if this is a bug or if it should’ve been submitted as a request. I’d just really like to have the inspection voice and yet be able to listen to music while timing

**Comment by pdtxie** [comment]
This was indeed a bug! Will release soon in a bug fix update.
