### ISSUE TITLE
“TO REACH TARGET FEATURE” not working in Comp Sim sessions

### ISSUE THREAD

**Issue by JudeStradtner** [CubeStuffs/CubeTime#147]
When the WPA is over the Target time, the “TO REACH TARGET” feature will display “NOT POSSIBLE”, even if the BPA is under the Target time.
“TO REACH TARGET” will also only display “GUARANTEED” if the BPA is under Target time, even if WPA is over Target time.
![IMG_2860](https://user-images.githubusercontent.com/108846175/226753430-009ff50a-5dcf-4d2a-abde-0d1d6f512034.png)

**Comment by pdtxie** [comment]
This has been fixed in coming update v2.1 (https://github.com/CubeStuffs/CubeTime/commit/19f235cad44bf1b545f56560e2d304be508ae43a)
