### ISSUE TITLE
Only two columns in "Times" with an empty middle column

### ISSUE THREAD

**Issue by root2over2** [CubeStuffs/CubeTime#149]
**Describe the bug**
There are only two columns in the "Times" section of the app (the second menu item).

**To Reproduce**
1. Go to the App
2. Click on the second menu itme

**Expected behavior**
We should see three columns, rather than two.

**Smartphone (please complete the following information):**
 - iPhone 11 Pro Max
 - OS: iOS16
 - App version: the newest one

**Comment by pdtxie** [comment]
sorry about this! fixed in v2.1.2 (https://github.com/CubeStuffs/CubeTime/commit/612329fe2663e6e592bb1d93bf19fbe0dfed3ec4). I've uploaded to AppStore, but it always takes a while for it to be reviewed and stuff
