### ISSUE TITLE
Repeated Scrambles

### ISSUE THREAD

**Issue by nheavilin** [CubeStuffs/CubeTime#153]
My last 15-20 scrambles have been the same

**Comment by pdtxie** [comment]
did you lock the scramble?

**Comment by pdtxie** [comment]
@nheavilin if you did not lock the scramble and are still experiencing this issue, it would be good if you could attach some screenshots, provide me the app version, your iOS version and your phone model. Also could you attach what you were doing, up till it started producing the same scrambles? Thanks :)

**Comment by xbjfk** [comment]
Closing, since it has been a year with no response. If you are still experiencing this, please re-open this issue.
