### ISSUE TITLE
Deleted solves included in session mean

### ISSUE THREAD

**Issue by pancak3bunny** [CubeStuffs/CubeTime#154]
**Describe the bug**
After deleting the most recent solve using the gesture commands on the timer screen, the session mean will continue to include the deleted solve until either the app is restarted or a different session is opened. 

**To Reproduce**
1. Create a new standard session 
2. Complete a solve in the new session
3. Swipe left to delete the solve
4. Mean fails to update

**Expected behavior**
After deleting the solve, the session mean should automatically update like the Ao5, Ao12, etc. do.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 16.3.1
 - App version: 2.0

**Comment by pdtxie** [comment]
Update the v2.1.2, this issue was fixed in the later versions :)
