### ISSUE TITLE
Settings do not save after v2.1.2 update

### ISSUE THREAD

**Issue by JustinCuber** [CubeStuffs/CubeTime#155]
**Describe the bug**
after the latest update the settings have been changed back to default and I cannot change anything.

**Comment by pdtxie** [comment]
Are you logged into iCloud? This may be a serious issue @xbjfk can you investigate further..?

**Comment by pdtxie** [comment]
Also @JustinCuber could you please provide additional info - could you confirm this is the v2.1.2 update, and if you were logged into iCloud before.

**Comment by JustinCuber** [comment]
Yes it is V2.1.2, and I am logged into iCloud. On an IPhone 14. Basically when I opened the app this morning it showed the update but the settings had gone back to default and I am not able to change anything. Any time I hit a button on anything in settings it doesn’t work.

**Comment by pdtxie** [comment]
Right that's concerning. Was it working fine before the v2.1.2 update?

**Comment by JustinCuber** [comment]
Yes, no issues whatsoever. And just to explain more, when I hit a button there is haptic response but the setting itself does not change. Same for the +/- buttons. I get a haptic but that’s it.

**Comment by pdtxie** [comment]
We were getting this issue while testing iCloud sync for settings, but seemed to have fixed it before releasing. Are you using more than one device with cubetime or just your phone?

**Comment by JustinCuber** [comment]
Just my phone

**Comment by JustinCuber** [comment]
Update. I restarted my phone and it’s working now.

**Comment by pdtxie** [comment]
Oh awesome, closing this issue then :)
