### ISSUE TITLE
Time Trend only showing last 80 solves

### ISSUE THREAD

**Issue by PizzaCuber1** [CubeStuffs/CubeTime#156]
The time trend graph no longer shows every solve in the session like it used to. 
![1E0B32D5-349B-4BA9-B802-DBE9325329D3](https://user-images.githubusercontent.com/129327040/228643050-076649da-3573-482d-9753-e734b8e5c334.png)
This is my 4x4 session with 2300 solves but the graph doesn’t show them all anymore. Before this last update it showed all of the solves which showed an accurate representation of improvement.

**Comment by pdtxie** [comment]
Yes this is intended behaviour, it is currently set to show the last 80 solves in your session. This was done to improve performance. We’re re-adding the entire session time trend through an interactive graph in the next update :)

**Comment by xbjfk** [comment]
In v3, you can now tap the graph and reveal a large graph with all your solves.
