### ISSUE TITLE
Time Distribution showing duplicate intervals due to rounding

### ISSUE THREAD

**Issue by NevisaurusRex** [CubeStuffs/CubeTime#158]
**Describe the bug**
Certain time categories are duplicated in the distribution chart

**To Reproduce**
1. Go to 'stats'
2. Scroll down to 'time distribution’
3. See error

**Expected behavior**
There should be mo duplicated time categories

**Screenshots or screen recordings**
![8FE483DA-BACB-4BA2-BFBC-575542E6BC49](https://user-images.githubusercontent.com/129645676/229334255-ae26da4d-927a-4ab8-8822-303444da764b.jpeg)

**Crash log if applicable**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone SE V2]
 - OS: [e.g. iOS 16.1.1]
 - App version [e.g. 2.1.2]

**Additional context**
my 13+ category is duplicated on the chart, as shown in the screenshot

**Comment by pdtxie** [comment]
Yeah this is because of rounding issues (like 12.6 ~ 13.4 will all round to 13)
I'll keep this open as an interactive time distribution graph is in the works.

**Comment by pdtxie** [comment]
Closing as merging with previous issue
