### ISSUE TITLE
[Feature] Generate new scramble on swipe/tap on scramble

### ISSUE THREAD

**Issue by marotirobi97** [CubeStuffs/CubeTime#163]
I understand that currently, pressing the scramble button shows the actual scramble with an image. However, in my opinion, it would be better if pressing the scramble would generated a new scramble, while pressing the image of the scramble would display the current scramble with an image of the scramble. I hope its clear what i meant to say.

**Comment by pdtxie** [comment]
You can generate a new scramble by swiping right.

**Comment by marotirobi97** [comment]
I didn't know that, sorry. I tried it and unfortunately, it's not working out quite well for me because I accidentally start the timer sometimes. Perhaps it would be better if that it only generates a new scramble when swiping right on the scramble and not on the timer. What do you think?

**Comment by pdtxie** [comment]
I see. We may add this as an accessibility feature in the future. As for now, you can also try customising the gesture activation distance and/or the hold down time as to reduce the chance of accidentally starting the timer when swiping.

**Comment by pdtxie** [comment]
Closed as not planned
