### ISSUE TITLE
Multiphase session crashes after moving a regular solve into it

### ISSUE THREAD

**Issue by DaHawk27** [CubeStuffs/CubeTime#168]
**Describe the bug**
App goes to the Home Screen when selecting a multiphase session after moving a single phase time to it. 

**To Reproduce**
1. Click on a best single time from a single phase session. 
2. Click on move to different session. 
3. Click a multiphase session. 
4. Now when you try to switch to that session app “crashes” and take me back to the Home Screen. 

**Expected behavior**
When I tap on the new session I expect to see the best single scramble and time in the new session. 

**Screenshots or screen recordings**

https://github.com/CubeStuffs/CubeTime/assets/138076839/210fe610-d382-4b9c-9074-225e81233c18

**Crash log if applicable**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.5.1
 - App version 2.1.2

**Additional context**
I moved a single phase time to a multiphase time trying to copy the scramble over to the multiphase session in order to recreate the solve with the multiphase breakdown.

**Comment by pdtxie** [comment]
Hey there, really sorry that this has happened - we thought we had prevented moving solves between regular sessions and multiphase sessions. Unfortunately this is not supposed to happen, and the app is probably crashing as it's trying to calculate phase times for an undefined number of phases. 

We'll look into adding something that can "fix" these broken sessions, but as for now I'm afraid there is nothing we can do.

**Comment by DaHawk27** [comment]
Hey it’s all good! I kind of figured that’s why the app was crashing. Is it
possible for me to recover that time back onto the original session? And if
so how would I go about doing that? If that’s not possible, no worries at
all I screenshotted the scramble so it’s not forever lost lol.

Thank you so much for reaching out!!

**Comment by pdtxie** [comment]
sorry about this - we've now fixed the crashing (3840b7946e7b458d457c7f1fc313787a2a381a0a), and so you should be able to re-enter the multiphase session. we've also prevented this from happening in the future.
