### ISSUE TITLE
Can’t switch sessions on iPad iOS 

### ISSUE THREAD

**Issue by penguin-awsome** [CubeStuffs/CubeTime#170]
I simply just cannot find a way to switch my session on iPad iOS 16.5.1

In the main menu, I can’t switch my session, or create new ones, but everything else works.

Just really annoying, ‘cause I used to be able to.

![IMG_0265](https://github.com/CubeStuffs/CubeTime/assets/139717895/e96610af-ef59-48d9-a64e-e23f44f20314)

It’s possible I am an idiot, and just can’t find it, but I have been searching for a while in the app.

**Comment by pdtxie** [comment]
Sorry if the new interface is confusing, you can drag the little dragger on the bottom of the times to reveal the session button. We will aim to add a user guide in the near future.
