### ISSUE TITLE
Settings unresponsive on iPad due to iCloud

### ISSUE THREAD

**Issue by FrederickCMorrison** [CubeStuffs/CubeTime#174]
**Describe the bug**
On the iPad Air gen 5, the settings menu is completely unresponsive.

**To Reproduce**
1. Go to the settings menu 
2. Click on any settings option
3. The setting doesn’t change

**Expected behavior**
You should be able to change the settings

**Screenshots or screen recordings**
https://github.com/CubeStuffs/CubeTime/assets/140788296/9eb88d4e-99f3-4fbd-808a-e4e59cfee654

 - Device: iPad Air gen 5
 - OS: iPadOS 16.1.1
 - App version v2.1.2

**Additional context**
This happens with both tapping on the options and clicking using the mouse on the Apple Magic Keyboard. This does not happen on all of my apple devices, as the app works perfectly on my iPhone 11, on which I can change the settings, the settings however do not save to iCloud, but I assume that is intentional in order to have per-device settings and am just pointing it out in case it is not.

I have tried to uninstall and reinstall the app and it hasn’t fixed the issue.

**Comment by pdtxie** [comment]
That is very strange, the settings should be syncing across devices. We first observed this behaviour during development, but @xbjfk fixed it soon after. I'm not sure if this is the same problem...

If you don't have many solves / aren't too worried about losing solves, could you try to turn off iCloud for CubeTime in system settings, and turn it back on? (should be under iCloud > iCloud > (Apps using iCloud) Show All > CubeTime)

**Comment by FrederickCMorrison** [comment]
Unfortunately, this did not fix the issue, it weirdly enough still kept my previous times. However, It did create a new “default playground”. The settings still aren’t saving over iCloud and still none of the settings can be changed on the iPad.

**Comment by pdtxie** [comment]
I see. Roughly when did this start happening? Have the settings been broken since the iCloud/v2 release, or did it only break just recently?

Could you also try to go to iCloud > Manage Account Storage > CubeTime > Delete data? This will definitely wipe all your sessions/solves, so I understand if you do not wish to do so.

**Comment by FrederickCMorrison** [comment]
I’m not sure when this started happening, I only started getting back in to speedcubing a few days ago, and hadn’t used this app on my iPad before. I had used it before on my iPhone a while back but this time I wanted to use my stackmat timer and tried to change the timer option to “typing”, when I encountered this bug.

I just tried deleting the iCloud data and all of the previous issues persist.

**Comment by FrederickCMorrison** [comment]
Oh I just updated my iPadOS to the latest version, 16.6, and it fixed this issue. Sorry for making a bug report when it was my fault.

**Comment by pdtxie** [comment]
I’m very glad to hear that it’s working now! It’s possible that it was an Apple problem, and they happened to fix it. I’m going to leave this issue open in case any other people run into the same problem.

**Comment by pdtxie** [comment]
closing as most people as most people should be using >=16.6 now
