### ISSUE TITLE
iCloud sync not working

### ISSUE THREAD

**Issue by EpicGreenMARS** [CubeStuffs/CubeTime#175]
How do you connect devices with iCloud?
My 2 devices don’t sync my times and I can’t find a setting to turn it on/off. How do I fix this?

**Comment by pdtxie** [comment]
iCloud has frankly been a huge pain on our behalf to implement, and many users are experiencing issues. We hope to be able to issue a fix soon, but we are yet to locate the issue.

If both your devices are logged into the same account, and have CubeTime turned on in iCloud, then it should work.

**Comment by EpicGreenMARS** [comment]
Thanks, I just had to explore the iPad app a bit further, and I found all of my solves. Not a problem with iCloud, just a problem with me!

**Comment by pdtxie** [comment]
Oh cool, will close this issue then :)
