### ISSUE TITLE
Truncate vs round

### ISSUE THREAD

**Issue by SuperPro148** [CubeStuffs/CubeTime#177]
Hey, I noticed that the time updater rounds rather than truncates when it has less decimals than the actual time. I use 2 decimals for time and 1 decimal while timing but for example when the time is 18.77 when I stop the timer, it shows 18.8 shortly before pressing. I suspect this is due to rounding the time rather than truncating it.

**Comment by pdtxie** [comment]
That’s an interesting observation, I haven’t noticed it myself. Will look into this issue.

**Comment by pdtxie** [comment]
Ok I can reproduce. Seems that the time needs to be truncated first, then have the it formatted in the string. Format specifiers round by default!

**Comment by xbjfk** [comment]
Fixed (see also #187)
