### ISSUE TITLE
Choose between mean of 3 or average of 5 for comp sim

### ISSUE THREAD

**Issue by Ysparky** [CubeStuffs/CubeTime#178]
**Is your feature request related to a problem? Please describe if applicable.**
When creating Comp Sim session, it should request user to choose between average of 5 or mean of 3.
In this way users can also simulate categories that are officially calculated with a mean of 3 like big cubes eg 6x6 or 7x7

**Comment by pdtxie** [comment]
duplicate of https://github.com/CubeStuffs/CubeTime/issues/89
