### ISSUE TITLE
Timer update 0 d.p display with added 0

### ISSUE THREAD

**Issue by 00Greg** [CubeStuffs/CubeTime#186]
1. timer settings: timer update 0 d.p
2. Start timer
3. Wait for >59 s
4. Display shows additional leading 0 for the seconds counting up, e.g. “1:012“ for 72 s, “1:059“ for 119 s

expected: 
“1:12“ for 72 s, “1:59“ for 119 s

At a glance I always think I‘m at the beginning of the minute. I get dropped into reality when I stop the timer .. :-)

**Comment by pdtxie** [comment]
fixed in https://github.com/CubeStuffs/CubeTime/commit/277c5ffbf6f7efd8ba0cd3f605e5f55e4b5bbc22
