### ISSUE TITLE
Time approximation

### ISSUE THREAD

**Issue by Tremola69** [CubeStuffs/CubeTime#187]
I see that the app often approximates times , like a 7.999 to a 8.00 , this isn’t good.

If you get a time from X.xx8 to X.xx9 it approximates the time 

I would like to just see the millisecond time cut off , not approximated
iPhone 13 Pro 

https://github.com/CubeStuffs/CubeTime/assets/156473829/d57eab0b-bcfc-449c-8c37-c423650f9bed

**Comment by pdtxie** [comment]
fixed in 8b2e3d4
