### ISSUE TITLE
Customizable gestures

### ISSUE THREAD

**Issue by xbjfk** [CubeStuffs/CubeTime#2]
- [x] general settings
- [x] gradient setting
- [x] fix color settings
- [ ] customize gestures
- [ ] iPad keybinds
- [x] app icon
- [x] statistics display mode 2dp/3dp
- [x] update interval time

**Comment by pdtxie** [comment]
merged with https://github.com/CubeStuffs/CubeTime/issues/6#issue-1079727981

**Comment by xbjfk** [comment]
still need customizable gestures!

**Comment by pdtxie** [comment]
I MERGED
