### ISSUE TITLE
Average Calculator-can’t continue to next solve 

### ISSUE THREAD

**Issue by hihoman23** [CubeStuffs/CubeTime#205]
Maybe I’m just blind, but I can’t return after entering the first solve

**To Reproduce**
1. Go to the average calculator
3. Type in a time

**Expected behavior**
There should be a button when I can continue to the next solve or see my average.

**Screenshots or screen recordings**
![IMG_0323](https://github.com/CubeStuffs/CubeTime/assets/78002940/4cdce546-700e-402e-bb62-60541510580c)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.3.1 (21D61)
 - App version: v3.0.0

**Comment by pdtxie** [comment]
Sorry about this, this is seems to be an Apple issue from iOS 17+. We will look into this
