### ISSUE TITLE
Time Distribution Graph Acting Erratically 

### ISSUE THREAD

**Issue by whatupo9** [CubeStuffs/CubeTime#207]
Based on my current solve distribution, my graph has a lower bound of <13, and an upper bound of >19. I will be using these numbers to explain the issue, and this is what I am referring to. 

The chart as it is now:
![IMG_3070](https://github.com/CubeStuffs/CubeTime/assets/131555269/732d3684-e11a-49d2-9d97-c72b436f76ac)

My time distribution chart has the same numbers listed for both the greater than 19 seconds, and less than 13 seconds. Also, the less than column, which should increment for each solve less than 13(for me), only increases when the solve is less than 13, but greater than 12.

When I get a solve that is between 12 and 13, both columns of the graph will sometimes increment, but sometimes the 13+ column will, like in the next example.

After a 12.085 solve:
![IMG_3069](https://github.com/CubeStuffs/CubeTime/assets/131555269/e346405c-1cf9-4eff-bd09-de93fe675f1a)

When I get a solve less than 12, or greater than 19, the graph remains unchanged most of the time, but also sometimes change the 13+ column.
 
 After a 8.933 second solve:
![IMG_3071](https://github.com/CubeStuffs/CubeTime/assets/131555269/6dea2e50-6c7a-42a9-a858-0599b50eff7f)

After a 5.260 second solve:
![IMG_3072](https://github.com/CubeStuffs/CubeTime/assets/131555269/da7c8beb-382e-49fa-86fa-b3147bfa3d48)

I don’t have a good idea for how to reproduce this, but this is in a playground session with only 3x3 solves, with over 4500 solves. I noticed it started around 1000 solves, and it hasn’t changed even though
the numbers at the upper and lower bounds have changed based on my improvements.

I expected that whenever I got a solve less than 13, then that column would go up, and the rest would remain the same, and if I got a solve greater than 19, that would be the only column to change.

**Screen recordings**
Here’s a video of a few “solves” in a row, showing the issue. The 13+ category is at one point up to 447, then it drops down to 432, and then jumps back up to 444. And the upper and lower columns only change once, despite every solve being above or below the threshold.

https://github.com/CubeStuffs/CubeTime/assets/131555269/a172e181-7a4a-4f3e-a805-64ee6bf89ca6

**Versions and Device**
 - iPhone 8
 - IOS 16.7.5
 - CubeTime v3.0.0

**Comment by whatupo9** [comment]
Sounds good, it’s not causing me that much trouble, I just wanted to make sure that you guys were aware of it. Love the app, can’t wait for more features,-Cameron On Apr 1, 2024, at 15:28, Tim Xie ***@***.***> wrote:﻿
Yeah essentially the issue is that the bins are fixed widths, but we round to 0dp. So the bins may start to shift size, and so this behaviour occurs. We will be building a better solve distribution soon. Sorry about this

**Comment by pdtxie** [comment]
Closing as merging with previous issues
