### ISSUE TITLE
Problem with milliseconds when typing in time

### ISSUE THREAD

**Issue by megacuber** [CubeStuffs/CubeTime#211]
When I type in my time instead of using the app timer, I can't add 3 digits in the milliseconds. Instead, a digit is moved into the minutes. For example, when I try to add a time of 4:01.418, the app instead recognizes it as 40:14.18. If I just round off my milliseconds and type in 4:01:42, the app adds on a zero to the end of the milliseconds and displays it as 4:01.420.  So it's set up for 3 millisecond digits, but doesn't correctly accept that 3rd digit when typed in.

I'm using an iPad 9th generation, iOS 17.4.1.

![IMG_0248](https://github.com/CubeStuffs/CubeTime/assets/163602653/57c0161b-79fa-4de6-8e6c-904d6e21d5b1)
![IMG_0249](https://github.com/CubeStuffs/CubeTime/assets/163602653/2b644e1f-73f6-4478-81c7-60f51ee3cb58)
![IMG_0250](https://github.com/CubeStuffs/CubeTime/assets/163602653/78609090-c992-4db5-b66a-f6066b78c5ce)

**Comment by pdtxie** [comment]
The motivation behind this design choice is that WCA competitions only record up to 2d.p. in data entry. We may add a 3d.p. input time option in the future.
