### ISSUE TITLE
Idea/Suggestion: Ability to move solves between sessions

### ISSUE THREAD

**Issue by Wardeneo** [CubeStuffs/CubeTime#37]
Firstly I’d like to add todays update with the scramble graphic and screen timeout block during solves are great additions! 👍🏾

Whilst using the app today I did a couple of solves and realised I was in wrong session (I have multiple sessions for different cubes). I’d like to be able to move a solve from 1 session to another, not just the ability to delete solves

cheers Wardeneo

**Comment by pdtxie** [comment]
Transferred to #58.
