### ISSUE TITLE
Idea/Suggestion: Display the Session Name At Top of app

### ISSUE THREAD

**Issue by Wardeneo** [CubeStuffs/CubeTime#40]
Another suggestion for future update would be to display the session name in top of app - so instead of just saying “standard session” it would display session name instead.

or better still it could display both session type and name?

as always great work, love the app

cheers Wardeneo 

![8EFB2A57-7B52-427F-907B-2ADFA993A317](https://user-images.githubusercontent.com/98850700/152705299-fa82e117-bd8f-4ef8-a076-cffaa5e6f093.jpeg)

**Comment by pdtxie** [comment]
Thanks for this suggestion! I've come up with a preliminary design, but it's not as intuitive as I would have liked. Any feedback is greatly appreciated!

https://user-images.githubusercontent.com/65262710/187179294-21474a19-9022-40c4-92f8-5f981979ffb7.mov

**Comment by Wardeneo** [comment]
Hi mate, had a look at the video, is there any way to just have session name displayed all the time as tapping on the icon to reveal the name is takes just as long to tap on the circle icon with 3 lines at bottom and seeing which session is highlighted.

I have loads of sessions for different cubes and training sessions so knowing which one I’m in at a glance is helpful.


Further on to this I made a suggestion few months back about moving solves to a different session, has that had any further progress?

Also on the session selection screen, could it be made even clearer which session is highlighted please

sorry for the bombardment of feedback, I’m loving the app… still the best Speedcube app for me 👌🏾

Cheers liam

**Comment by Wardeneo** [comment]
![10293E5E-C81F-4E82-8815-820E29905F0F](https://user-images.githubusercontent.com/98850700/187191573-9e1214e0-1918-49d5-8d38-837c5166e7e2.jpeg)
![15780D80-8CF8-4F72-AD43-745279BFE5E6](https://user-images.githubusercontent.com/98850700/187191579-3cd4583a-22df-4131-a21d-37528847448a.png)

**Comment by pdtxie** [comment]
Thank you so much for this! Feedback is always appreciated!

I agree with you – I'll add an option in settings to toggle display name, so that the session name can be displayed permanently without needing any user interaction.

As for moving solves between sessions, we haven't had a chance to implement this yet, but we've been drafting some designs for it, so it should be coming in the near future.

For the session highlight issue, I'll play around with some alternative designs, and I'll keep you updated!

**Comment by Wardeneo** [comment]
> Thank you so much for this! Feedback is always appreciated!
> 
> I agree with you – I'll add an option in settings to toggle display name, so that the session name can be displayed permanently without needing any user interaction.
> 
> As for moving solves between sessions, we haven't had a chance to implement this yet, but we've been drafting some designs for it, so it should be coming in the near future.
> 
> For the session highlight issue, I'll play around with some alternative designs, and I'll keep you updated!

Ok mate, I’ll await the updates, thanks liam

**Comment by pdtxie** [comment]
@Wardeneo I've added a settings toggle to permanently display the session name.
![image](https://user-images.githubusercontent.com/65262710/187633730-5b9d6b0a-0a45-4472-aab8-c2c4932f7293.png)

If this is toggled on, you'll always see the session name. You can still tap the icon to temporarily toggle between the two though.
![image](https://user-images.githubusercontent.com/65262710/187633803-586a26a2-c391-4c5f-8036-113e09f76101.png)


I've lightened the background in dark mode, and added a small highlight.
![image](https://user-images.githubusercontent.com/65262710/187639624-69c1fb4f-4e9c-48d8-bc9f-9978e171eb1e.png)

**Comment by pdtxie** [comment]
Should be soon, we've got a couple more features planned, and should be scheduled to release in the next week or two.

**Comment by Wardeneo** [comment]
> Should be soon, we've got a couple more features planned so it should be scheduled to release in the next week or two.

Ok cheers mate

**Comment by Wardeneo** [comment]
Hi, when is this feature being released into the app?

**Comment by pdtxie** [comment]
Hi – incredibly sorry, we're both in the middle of exams, thought we could push the update before but had some other things on. We'll aim to push this as soon as we finish exams – should be in about 1-2 weeks. Really really sorry! I'll reopen this so I don't forget :)

**Comment by Wardeneo** [comment]
> Hi – incredibly sorry, we're both in the middle of exams, thought we could push the update before but had some other things on. We'll aim to push this as soon as we finish exams – should be in about 1-2 weeks. Really really sorry! I'll reopen this so I don't forget :)

Ahh ok, no worries mate 👌🏾

**Comment by pdtxie** [comment]
Added in v2.0 to be released this week.

**Comment by Wardeneo** [comment]
Hi sorry to pester you, when is v2 coming out?

**Comment by pdtxie** [comment]
Whoops, way too many things happened this month -- thought I was going to be able to push then. Currently I'm hoping for early-mid January. I've been hesitant to push as we almost re-wrote the entire backend and haven't extensively tested it at all... I will revisit this in about two days, and see if I can finalise to push.

**Comment by Wardeneo** [comment]
> Whoops, way too many things happened this month -- thought I was going to be able to push then. Currently I'm hoping for early-mid January. I've been hesitant to push as we almost re-wrote the entire backend and haven't extensively tested it at all... I will revisit this in about two days, and see if I can finalise to push.

👌🏾 Thank You 🙏🏾

**Comment by xbjfk** [comment]
We are hoping to push this update soon, for real this time.
