### ISSUE TITLE
very odd animation where whole stats page floats in

### ISSUE THREAD

**Issue by pdtxie** [CubeStuffs/CubeTime#48]
Seems to only occur in versions > iOS 15.2

**Comment by DTRW919** [comment]
The same thing happens to me in the stats screen right after I delete a session. It floats in from the top left.

**Comment by pdtxie** [comment]
Have notified this, and looking to fix. It looks like an issue updating to iOS 15.4, as it seems some animation modifiers have been changed.

**Comment by pdtxie** [comment]
@DTRW919 I've attempted a fix, are you able to join Testflight to test?

**Comment by pdtxie** [comment]
i’m closing this for now, if it comes up again,  open a new issue.

**Comment by DTRW919** [comment]
Sorry, I didn't see this, is there a testflight link I can use?

**Comment by pdtxie** [comment]
The new public update has been processed. Has been fixed there.
