### ISSUE TITLE
Timer Inspection Issue

### ISSUE THREAD

**Issue by KeanBarzaga** [CubeStuffs/CubeTime#55]
I have an issue for the timer. Whenever I stop the timer it starts inspection again and I can’t stop it. I would really like it if you add a button that stops inspection.

**Comment by pdtxie** [comment]
(53431224df570fc2279fc0a9772dbd94ce6fdb81) Added ability to stop inspection without generating a new scramble

**Comment by pdtxie** [comment]
I'm still unable to reproduce the bug where inspection starts immediately after stopping the timer. If you are able to provide steps to reproduce, or a video, I'll re-open the issue to have another look. As for now, I'm keeping this issue closed.
