### ISSUE TITLE
BUG: 7x7 oom crash

### ISSUE THREAD

**Issue by pdtxie** [CubeStuffs/CubeTime#57]
high priority issue

- 7x7 seems to be using OVER A 1.3Gb OF RAM???????????????????
  - tnoodle itself uses <100Mb 

possible solutions:
- check optimisation in j2objc
- rewrite in c++/swift

**Comment by xbjfk** [comment]
now only 600mb by switching to ARC, still very bad and worth writing a custom scrambler

**Comment by xbjfk** [comment]
fixed
