### ISSUE TITLE
Transfer solves between sessions

### ISSUE THREAD

**Issue by pdtxie** [CubeStuffs/CubeTime#58]
### Discussed in https://github.com/CubeStuffs/CubeTime/discussions/38

- needs to be same scramble type (but also anyType <-> playground)
- compsim not transferrable to other types - but can between comp sim?? transfer groups maybe?
- check multiphase : must be same number of phases

**Comment by Wardeneo** [comment]
Is this coming in V2 as well??  Or a later update?

**Comment by pdtxie** [comment]
not sure, will consider if I have enough time to write it + test

**Comment by xbjfk** [comment]
Coming in v2, releasing soon :tm:
