### ISSUE TITLE
Preliminary iPadOS support

### ISSUE THREAD

**Issue by xbjfk** [CubeStuffs/CubeTime#6]
- [x] Implement horizontal iphone design alongside
- [x] floating panel support with timelistview and sessionsview
- [x] keyboard support - shortcuts and space to time
- [x] multitask window support -> different designs - responsive
- [x] trackpad gesutres
- [x] full entry mode
- [x] gestures (incl. swiping too, both ipad and iOS)
  - [ ] customizable
- [x] keyboard shortcuts
  - [ ] customizable
  - [ ] fix when time list is displayed
- [ ] macOS support
(https://github.com/CubeStuffs/CubeTime/issues/82)

**Comment by pdtxie** [comment]
hi @heytherewill, thank you! I'm currently still working on the iPad interface itself and haven't started on CloudKit support yet. If it isn't too much trouble for you, absolutely!

**Comment by heytherewill** [comment]
Nice! 

In order to help you with CloudKit, we would need sync about the changes to be made on the developer console. Hit me up on heytherewill at gmail.com so we can chat about it!

**Comment by pdtxie** [comment]
Sounds good!
