### ISSUE TITLE
I open it and it closes 

### ISSUE THREAD

**Issue by TheIceCuber** [CubeStuffs/CubeTime#62]
As I said in the title as soon as I open the app it crashes and I’m on iPod touch 7th generation running Version 15.4.1

https://user-images.githubusercontent.com/107078665/172481966-db12fae0-4c47-4c19-bd23-05930f17b64e.MOV

**Comment by pdtxie** [comment]
Hi – we’re really sorry for this. We’re still looking at the cause of this issue – it will hopefully be fixed soon.

**Comment by xbjfk** [comment]
I am pretty confident this will be fixed in the next update due to the significantly lower memory usage, please reopen if this still occurs
