### ISSUE TITLE
Can't see what I'm typing when I'm typing a comment

### ISSUE THREAD

**Issue by Abhay909** [CubeStuffs/CubeTime#70]
This is a problem where I can't see what I'm typing when commenting on a solve. I usually mess up and it's hard to go back and fix it because I can't see what I'm typing.

Can you add a thing so that you can see what your typing?

For example in DC timer you can see what you are commenting while you are typing 

https://user-images.githubusercontent.com/87679962/183488250-1df63dad-2d9d-4c85-9c20-f1a34bf04372.MOV

**Comment by pdtxie** [comment]
You should be able to scroll down even when the keyboard is up, to see the comment box.
I will see if I can push an update to force focus on the comment box, as for now, please just scroll down to the comment area to see what you're typing.
Thanks
