### ISSUE TITLE
I would like for the fastest solve to show first.

### ISSUE THREAD

**Issue by Abhay909** [CubeStuffs/CubeTime#71]
I'm always frustrated when I have to scroll all the way down to see my best solves.

** when you say sort by time I want the best solve to be on top.

![image](https://user-images.githubusercontent.com/87679962/183497992-8e6942d2-e03b-4b0f-8ca3-4723a93ddeee.png)

**Comment by pdtxie** [comment]
Yes, press the arrow on the right of the Sort by Time/date 
![image](https://user-images.githubusercontent.com/65262710/183588206-dea55d5c-5035-4a60-9ae2-b48333b26fbc.png)

This allows you to toggle your times in ascending/descending order of speed or date.
