### ISSUE TITLE
Other session types/timer functions

### ISSUE THREAD

**Issue by xbjfk** [CubeStuffs/CubeTime#8]
- [x] playground session
    - [x] create this as default session
    - [x] puzzle/event selector in stats, timer, and time list view
- [x] comp sim mode
    - [x] 5 solves at a time
    - [x] gives you ALL the stats about an ao5: bpa, wpa, time needed for x, time needed to secure x, median, avg, best time worst time, mean
    - [x] in the time list, instead of having individual solves, you have each average displayed, and you can click on them to see the times involved, with the best solve highlighted and in brackets and whatever 
    - [x] non rolling session
    - [x] stats and graphs based off of averages
    - [x] target
    - [x] ability to delete current comp sim average with gesture or something
- [ ] alg trainer (make new issue)
- [x] multiphase
    - [x] ability to create from new session
    - [x] ^ from timer view
    - [x] stats shows phases
    - [ ] you can choose phase to view in time list (after release)

**Comment by xbjfk** [comment]
@pdtxie can we close this since we have a separate issue for alg trainer?
is " you can choose phase to view in time list (after release)" done?

**Comment by pdtxie** [comment]
@xbjfk yes we can close this, i'll open a separate issue for phase view feature.
