### ISSUE TITLE
Sound alert when inspection time is up

### ISSUE THREAD

**Issue by fun4stuff** [CubeStuffs/CubeTime#81]
None of the iOS apps have this. 

This would be great because i don't want to have to keep my eye on the app. 

It seems like it should be easy to implement and an obvious feature to have..., yet no one has thought of this?

**Comment by pdtxie** [comment]
yep it's been mentioned many times too – we've got exams coming up and should be able to add this after november. sorry!

**Comment by xbjfk** [comment]
coming next update
