### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by gbaranski** [CubeStuffs/CubeTime#82]
Hi, MacOS support would be great. And the data could be synchronised easily using iCloud and FileManager or NSUbiquitousKeyValueStore.

**Comment by pdtxie** [comment]
macOS support is planned in our more long-term roadmap. We hope to support macOS when we add  cloudkit support with the iPad version (releasing soon).

**Comment by xbjfk** [comment]
we can add preliminary support for macos (arm ones) alongside ipad mode by allowing apple's compatibility layer for ipados/ios

**Comment by pdtxie** [comment]
merged with https://github.com/CubeStuffs/CubeTime/issues/6#issue-1079727981
