### ISSUE TITLE
Bad Time Format - 1:60.00 - 1 minut and 60 second 

### ISSUE THREAD

**Issue by qbacuber** [CubeStuffs/CubeTime#83]
**Describe the bug**
I found an error in the way the time is written, it seems to me that `1:60.00` should already turn into `2:00.00`

If I manually enter a time of `1:60.00` it will be converted to `2:00.00`, but when I get this time by normal stacking there is no converted.

**To Reproduce**
1. Start the timer
2. Stop exactly at an even time, for example, at 60s

**Screenshots or screen recordings**
![image](https://user-images.githubusercontent.com/38834474/201538636-5e035458-675b-43cb-8a15-6ded84b78b8f.png)
![image](https://user-images.githubusercontent.com/38834474/201538701-a7e00798-2f5c-4689-8ce5-177e2c64130b.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro max 
 - OS: 16.1.1
 - App version 1.2.1

**Comment by pdtxie** [comment]
Hi - these are the bugs you can't pick up during testing! Thank you for this, I'll see if I can locate the issue. @xbjfk please see this issue too.
