### ISSUE TITLE
Mean on timer screen doesn't exclude DNFs

### ISSUE THREAD

**Issue by neelmehta247** [CubeStuffs/CubeTime#92]
**Describe the bug**

If a solve is DNFed it should not be counted in the mean. This is calculated correctly in the session stats page, but incorrectly on the timer page. 

**To Reproduce**
1. Start new session
2. Do a couple of solves
3. Do an extra solve and DNF it
4. Mean will now be lower than expected since it counts the solve as a time of 0.00
5. Go to session stats page and note that it's different 

**Expected behavior**
Should be the same as session stats page

**Comment by pdtxie** [comment]
Yes, has been fixed already (like 4-5 months ago), we just haven't had time to push it!!
