### ISSUE TITLE
Ability to clear session

### ISSUE THREAD

**Issue by neelmehta247** [CubeStuffs/CubeTime#93]
**Is your feature request related to a problem? Please describe if applicable.**
I like to clear sessions and start them from scratch. The only way to do this right now is to select every solve and delete it manually. Or create a new session. Both are not ideal and take more time than I'd like.

**Describe the solution you'd like**
Have a button to clear an existing session. 

**Reference, if applicable**
csTimer allows you to clear session.

**Comment by xbjfk** [comment]
Hi there, this will be coming in the next update. Here is how it will look:
![Screenshot 2023-02-25 at 9 31 18 PM](https://user-images.githubusercontent.com/24711088/221347397-98f3de87-872e-44c1-818b-b05eb12d28ca.png)
(this is the menu after entering select mode in time list)
