### ISSUE TITLE
Average

### ISSUE THREAD

**Issue by Balizkos** [CubeStuffs/CubeTime#94]
**Describe the bug**
My average of 5 (AO5) is inaccurate and producing an incorrect number.

**To Reproduce**
1. Set more than five times
2. Delete one or two of them (idk if this affects it but I know I deleted two of my times immediately after finishing)
3. Compute AO5 with calculator and compare to app’s AO5 time

**Expected behavior**
I expected a lower average when I completed a solve in less time than my time five attempts previously and my AO5 should have gone down but went up instead.

**Screenshots or screen recordings**

https://user-images.githubusercontent.com/121647797/210024569-29852689-13a8-428c-a580-5d35a57e38db.MOV

**Crash log if applicable**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11 pro]
 - OS: [e.g. iOS16]
 - App version [e.g. 1.2.1]

**Additional context**
I saw a bug where deleted solves aren’t removed from the AO5 or AO12 so that may be this bug but I thought I would submit the bug report anyways just in case.

**Comment by pdtxie** [comment]
Yes, this has been fixed already, we just haven't had the time to push the update 😭

**Comment by Balizkos** [comment]
> Yes, this has been fixed already, we just haven't had the time to push the update 😭

No worries. Good to hear. When do you think the update will get pushed out?

**Comment by pdtxie** [comment]
Hard to say currently, hoping for early-mid january.
